blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<str:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    
]

demosite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.urls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', 
                       args=[self.publish.year, 
                             self.publish.strftime('%m'), 
                             self.publish.strftime('%d'), 
                             self.slug])

    
    class Meta:
        ordering = ('-publish',)
        
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
        
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
'''
    Class-based views
'''
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'    
    
    
'''
    Function-based views
'''
# def post_list(request):
#     object_list = Post.published.all()
#     paginator = Paginator(object_list, 3)
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         posts = paginator.page(1)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     return render(
#         request, 
#         'blog/post/list.html',
#         {   'page': page,
#             'posts': posts}
#     )

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, 
        slug=post, 
        status='published', 
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)
    
    if request.method =='POST':
        # For posted comment
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        'blog/post/detail.html',
        {'post':post,
         'comments': comments,
         'comment_form': comment_form}
    )
    
'''
    To handle forms
'''

def post_share(request, post_id):
    post = get_object_or_404(Post, id = post_id, status= 'published')
    sent = False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        
        if form.is_valid():
            clean_dataform = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject ='{} ({}) recommends you reading "{}"'.format(clean_dataform['name'], 
                                                                  clean_dataform['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,
                                                                     post_url,
                                                                     clean_dataform['name'],
                                                                     clean_dataform['comments'])
            send_mail(subject, message, 'deepak.191708@ncit.edu.np', [clean_dataform['to']])
            sent = True
    else:
        form = EmailPostForm() 
        return render(request, 'blog/post/share.html',{'post': post,
                                                       'form': form,
                                                       'sent': sent})

blog/templates/blog/base.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>
            
            {% block title %}
        
            {% endblock title %}
                
        </title>
        <link href = " {% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id = "content">
            
            {% block content %}
                
            {% endblock content %}
                
        </div>

        <div id = "sidebar">
            <h2>
                BLOG
            </h2>
            <p>
                Example Blog
            </p>
                
        </div>
    </body>

</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock title %}


{% block content %}
    <link rel="stylesheet" href="{% static 'css/detail.css'%}">

    <h1>
        {{ post.title}}
    </h1>
    
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    
    <p class = "post">
    {{ post.body | linebreaks}}
    </p>

    <p>
        <a href = "{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    
    <span class = "comment">
        {% with comments.count as total_comments  %}
            <h2>
                {{ total_comments }} comment{{total_comments|pluralize}}
            </h2>
        {% endwith %}
            
    
        {% for comment in  comments %}
            <div class = "comment-content">
                <p class = "info">
                    Comment {{ forloop.counter }} by {{comment.name}}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks}}
            </div>
            {% empty %}
                <p>There are no comments yet.</p>
        {% endfor %}

        
        {% if new_comment %}
            <h2>
                Your comment has been added.
            </h2>
        {% else %}
            <h2>
                Add a new comment
            </h2>
            <form action="." method="POST" class ="comment-form">
                {{comment_form.as_p}}
                {% csrf_token %}
                <p>
                    <input type="submit" value ="Add Comment">
                </p>
            </form>
        {% endif %}
    </span>        
        
{% endblock content %}
    

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}
Blog

{% endblock title %}

{% block content %}    
    <link rel="stylesheet" href="{% static 'css/list.css'%}">
    
    <h1>
        Blog List
    </h1>
    {% for post in posts %}
        <h2>
            <a href = "{{ post.get_absolute_url }}">
                {{ post.title }}
        </h2>
        <p class = "date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body | truncatewords:30 | linebreaks}}
    {% endfor %}
<footer>    
    <p>
        {% include 'pagination.html' with page=page_obj %}
    </p>
</footer>

{% endblock content %}
    

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% load static %}


{% block title %}
    Share a post
{% endblock title %}
    

{% block content %}
<link rel="stylesheet" href="{% static 'css/share.css'%}">
    
    {% if sent %}
        <h1> E-mail Successfully sent</h1>

        <p>
            "{{ post.title }}" was Successfully sent to {{clean_dataform.to}}
        </p>
    {% else %}
        <h1>
            Share "{{ post.title }}" by e-mail
        </h1>
        <form action = "." method ="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value = "Send e-mail">
        </form>
    {% endif %}
{% endblock content %}
    

blog/templates/pagination.html
<div class = "pagination">
    <span class = "step-links">
        
        {% if page.has_previous %}
            <a href = "?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class = "current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        
        {% if page.has_next %}
            <a href = "?page={{ page.next_page_number }}">Next</a>
        {% endif %}
            
    </span>

</div>